version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0 # the primary container, where your job's commands are run
    working_directory: "~/todo-api"
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
  test:
    docker:
      - image: circleci/node:12.18.0 # the primary container, where your job's commands are run
    working_directory: "~/todo-api"
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
