version: 2.1

default_setup: &default_setup
  docker:
    - image: circleci/node:12.18.0
  working_directory: "~/todo-api"

jobs:
  setup:
    <<: *default_setup
    steps:
      - checkout
      - run: npm install
  test:
    <<: *default_setup
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test
workflows:
  version: 2
  setup_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
